package com.hzx.wms.greendao;

import android.database.Cursor;
import android.database.sqlite.SQLiteStatement;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.Property;
import org.greenrobot.greendao.internal.DaoConfig;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.database.DatabaseStatement;

import com.hzx.wms.bean.RepeatBean;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table "REPEAT_BEAN".
*/
public class RepeatBeanDao extends AbstractDao<RepeatBean, Void> {

    public static final String TABLENAME = "REPEAT_BEAN";

    /**
     * Properties of entity RepeatBean.<br/>
     * Can be used for QueryBuilder and for referencing column names.
     */
    public static class Properties {
        public final static Property Barcode = new Property(0, String.class, "barcode", false, "BARCODE");
    }


    public RepeatBeanDao(DaoConfig config) {
        super(config);
    }
    
    public RepeatBeanDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
    }

    /** Creates the underlying database table. */
    public static void createTable(Database db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "\"REPEAT_BEAN\" (" + //
                "\"BARCODE\" TEXT);"); // 0: barcode
    }

    /** Drops the underlying database table. */
    public static void dropTable(Database db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "\"REPEAT_BEAN\"";
        db.execSQL(sql);
    }

    @Override
    protected final void bindValues(DatabaseStatement stmt, RepeatBean entity) {
        stmt.clearBindings();
 
        String barcode = entity.getBarcode();
        if (barcode != null) {
            stmt.bindString(1, barcode);
        }
    }

    @Override
    protected final void bindValues(SQLiteStatement stmt, RepeatBean entity) {
        stmt.clearBindings();
 
        String barcode = entity.getBarcode();
        if (barcode != null) {
            stmt.bindString(1, barcode);
        }
    }

    @Override
    public Void readKey(Cursor cursor, int offset) {
        return null;
    }    

    @Override
    public RepeatBean readEntity(Cursor cursor, int offset) {
        RepeatBean entity = new RepeatBean( //
            cursor.isNull(offset + 0) ? null : cursor.getString(offset + 0) // barcode
        );
        return entity;
    }
     
    @Override
    public void readEntity(Cursor cursor, RepeatBean entity, int offset) {
        entity.setBarcode(cursor.isNull(offset + 0) ? null : cursor.getString(offset + 0));
     }
    
    @Override
    protected final Void updateKeyAfterInsert(RepeatBean entity, long rowId) {
        // Unsupported or missing PK type
        return null;
    }
    
    @Override
    public Void getKey(RepeatBean entity) {
        return null;
    }

    @Override
    public boolean hasKey(RepeatBean entity) {
        // TODO
        return false;
    }

    @Override
    protected final boolean isEntityUpdateable() {
        return true;
    }
    
}
